topic_lists_enabled: false
topic_lists:
  type: list
  default: ""
  description:
    en: "Comma separated title, query and max for each topic list."
direct_links:
  type: list
  default: ""
  description:
    en: "Sites to directly link to from the sidebar instead of linking to the topic."